name: Java CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            
            - name: Print cache key (pre-build)
              run: echo ${{ hashFiles('**/*.gradle') }}

            - name: Restore Gradle cache
              uses: actions/cache@v1
              with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-

            - name: Print cache key (post-build)
              run: echo ${{ hashFiles('**/*.gradle') }}

            - name: Build with Gradle
              run: ./gradlew build
